export const BALANCE = {
  // Time
  TICKS_PER_GAME_MONTH: 720,
  TICK_INTERVAL_MS: 1000,

  // Starting state
  STARTING_MONEY: 50_000,
  STARTING_REPUTATION: 50,

  // Rack
  DEFAULT_RACK_U: 42,
  DEFAULT_RACK_POWER_BUDGET: 5000,

  // Economy
  UPLINK_MONTHLY_COST: 500,
  REPAIR_COST: 200,

  // Failures
  PORT_FAILURE_CHANCE_PER_TICK: 0.0005,

  // SLA
  SLA_CHECK_INTERVAL_TICKS: 60,
  REPUTATION_GAIN_ON_SLA_MET: 0.1,
  REPUTATION_LOSS_ON_SLA_VIOLATION: 5,
  SATISFACTION_LOSS_ON_VIOLATION: 10,
  CHURN_SATISFACTION_THRESHOLD: 0,

  // Clients
  CLIENT_PROSPECT_INTERVAL_TICKS: 120,
  MAX_PROSPECTS: 3,
  PROSPECT_EXPIRE_TICKS: 240,
  REJECTION_REPUTATION_PENALTY: 1,
  BANDWIDTH_PER_CONNECTION: 10,

  // Congestion
  CONGESTION_THRESHOLD: 0.9,

  // Limits
  MAX_LOG_ENTRIES: 100,
  MAX_ALERTS: 50,
} as const;
